version: '3.7'
services:
  aws:
    image: localstack/localstack:latest
    container_name: aws
    ports:
      - '4566-4584:4566-4584'
    volumes:
      - 'aws-storage:/tmp/localstack'
    environment:
      - SERVICES=sqs,sns
      - DATA_DIR=/tmp/localstack/data
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  aws-storage: