package br.com.aws_project.adapter.outbound.i18;

public enum MessageProperties {
    API_FIELDS_INVALID,
    API_BODY_INVALID,
    INTERNAL_SERVER_ERROR,
    EDTECH_SERVICE_UNAVAILABLE_EXCEPTION,
    DUPLICATE_RESOURCE_EXCEPTION, EDTECH_NOT_FOUND
}
